/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_danielelvir;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabsPrincipales = new javax.swing.JTabbedPane();
        CrearVehiculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_Marca = new javax.swing.JTextField();
        ColorBttn = new javax.swing.JButton();
        tf_Modelo = new javax.swing.JTextField();
        PrecioVenta = new javax.swing.JTextField();
        AgregarVehiculo = new javax.swing.JButton();
        tf_Año = new javax.swing.JSpinner();
        CrearVendedor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_NombreVendedor = new javax.swing.JTextField();
        tf_CantidadCarros = new javax.swing.JSpinner();
        tf_CantidadDinero = new javax.swing.JTextField();
        AgregarVendedor = new javax.swing.JButton();
        CrearCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_NombreCliente = new javax.swing.JTextField();
        tf_Edad = new javax.swing.JSpinner();
        tf_Profesion = new javax.swing.JTextField();
        tf_CarrosComprados = new javax.swing.JSpinner();
        tf_SueldoDisponible = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CrearVentas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Te amo Nuila <3");
        setAlwaysOnTop(true);

        CrearVehiculo.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Marca");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Color");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Modelo");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Año");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Precio de Venta");

        ColorBttn.setText("Seleccione un Color");
        ColorBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorBttnActionPerformed(evt);
            }
        });

        AgregarVehiculo.setBackground(new java.awt.Color(102, 0, 102));
        AgregarVehiculo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        AgregarVehiculo.setText("AGREGUE VEHICULO");
        AgregarVehiculo.setActionCommand("AGREGUE Vehiculo");
        AgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearVehiculoLayout = new javax.swing.GroupLayout(CrearVehiculo);
        CrearVehiculo.setLayout(CrearVehiculoLayout);
        CrearVehiculoLayout.setHorizontalGroup(
            CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_Marca)
                    .addComponent(ColorBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(tf_Modelo)
                    .addComponent(PrecioVenta)
                    .addComponent(tf_Año))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearVehiculoLayout.createSequentialGroup()
                .addContainerGap(559, Short.MAX_VALUE)
                .addComponent(AgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        CrearVehiculoLayout.setVerticalGroup(
            CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVehiculoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ColorBttn))
                .addGap(20, 20, 20)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(CrearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(AgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        TabsPrincipales.addTab("Vehiculo", CrearVehiculo);

        CrearVendedor.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad de Carros Vendidos");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad de Dinero Generado");

        AgregarVendedor.setBackground(new java.awt.Color(153, 0, 153));
        AgregarVendedor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarVendedor.setForeground(new java.awt.Color(0, 0, 0));
        AgregarVendedor.setText("AGREGAR VENDEDOR");
        AgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearVendedorLayout = new javax.swing.GroupLayout(CrearVendedor);
        CrearVendedor.setLayout(CrearVendedorLayout);
        CrearVendedorLayout.setHorizontalGroup(
            CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVendedorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_NombreVendedor)
                    .addComponent(tf_CantidadCarros)
                    .addComponent(tf_CantidadDinero, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearVendedorLayout.createSequentialGroup()
                .addContainerGap(491, Short.MAX_VALUE)
                .addComponent(AgregarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        CrearVendedorLayout.setVerticalGroup(
            CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearVendedorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_NombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_CantidadCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(CrearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_CantidadDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(AgregarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        TabsPrincipales.addTab("Vendedor", CrearVendedor);

        CrearCliente.setBackground(new java.awt.Color(0, 102, 102));

        jLabel9.setText("Nombre");

        jLabel10.setText("Edad");

        jLabel11.setText("Profesion");

        jLabel12.setText("Cantidad de Carros Comprados");

        jLabel13.setText("Sueldo Disponible");

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("AGREGAR CLIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearClienteLayout = new javax.swing.GroupLayout(CrearCliente);
        CrearCliente.setLayout(CrearClienteLayout);
        CrearClienteLayout.setHorizontalGroup(
            CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearClienteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_NombreCliente)
                    .addComponent(tf_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Profesion)
                    .addComponent(tf_CarrosComprados, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_SueldoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearClienteLayout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        CrearClienteLayout.setVerticalGroup(
            CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearClienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CrearClienteLayout.createSequentialGroup()
                        .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_Profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12))
                    .addComponent(tf_CarrosComprados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(CrearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_SueldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        TabsPrincipales.addTab("Cliente", CrearCliente);

        javax.swing.GroupLayout CrearVentasLayout = new javax.swing.GroupLayout(CrearVentas);
        CrearVentas.setLayout(CrearVentasLayout);
        CrearVentasLayout.setHorizontalGroup(
            CrearVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 927, Short.MAX_VALUE)
        );
        CrearVentasLayout.setVerticalGroup(
            CrearVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        TabsPrincipales.addTab("Ventas", CrearVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsPrincipales)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsPrincipales)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColorBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorBttnActionPerformed
        ColorBttn.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.RED));
    }//GEN-LAST:event_ColorBttnActionPerformed

    private void AgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVehiculoActionPerformed
        try {
            String Marca = tf_Marca.getText();
            String Modelo = tf_Modelo.getText();
            Color color = ColorBttn.getBackground();
            int Año = (int) tf_Año.getValue();
            double Precio_Venta = Double.parseDouble(PrecioVenta.getText());

            vehiculos.add(new Vehiculo(Marca, color, Modelo, Año, Precio_Venta));

            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                File archivo = new File("./Vehiculo.txt");
                fw = new FileWriter(archivo, false);
                bw = new BufferedWriter(fw);
                for (Vehiculo t : vehiculos) {
                    bw.write("[\n"
                            + "\t" + t.getMarca() + ", \n"
                            + "\t" + t.getModelo() + ", \n"
                            + "\t" + t.getAño() + ", \n"
                            + "\t" + t.getPrecio_Venta() + ", \n"
                            + "]-\n");
                }
                bw.flush();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            bw.close();
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se agregó");
        }
        JOptionPane.showMessageDialog(this, "Se agregó exitosamente");
        tf_Marca.setText("");
        tf_Modelo.setText("");
        tf_Año.setValue(2000);
        PrecioVenta.setText("");
        ColorBttn.setBackground(Color.WHITE);
    }//GEN-LAST:event_AgregarVehiculoActionPerformed

    private void AgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVendedorActionPerformed
        try {
            String Nombre = tf_NombreVendedor.getText();
            int Cantidad_Carros = (int) tf_CantidadCarros.getValue();
            double Cantidad_Dinero = Double.parseDouble(tf_CantidadDinero.getText());

            vendededores.add(new Vendedor(Nombre, Cantidad_Carros, Cantidad_Dinero));

            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                File archivo = new File("./Vendedor.txt");
                fw = new FileWriter(archivo, false);
                bw = new BufferedWriter(fw);
                for (Vendedor t : vendededores) {
                    bw.write("[\n"
                            + "\t" + t.getNombre() + ", \n"
                            + "\t" + t.getCarros_Vendidos() + ", \n"
                            + "\t" + t.getDinero_Generado() + ", \n"
                            + "]-\n");
                }
                bw.flush();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            bw.close();
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error, no se agregó nada");
        }
        JOptionPane.showMessageDialog(this, "Vendedor agregado exitosamente");
        tf_NombreVendedor.setText("");
        tf_CantidadCarros.setValue(0);
        tf_CantidadDinero.setText("");
    }//GEN-LAST:event_AgregarVendedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String Nombre = tf_NombreCliente.getText();
            int Edad = (int) tf_Edad.getValue();
            String Profesion = tf_Profesion.getText();
            int Carros_Comprados = (int) tf_CarrosComprados.getValue();
            double Sueldo = Double.parseDouble(tf_SueldoDisponible.getText());

            clientes.add(new Cliente(Nombre, Edad, Profesion, Carros_Comprados, Sueldo));

            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                File archivo = new File("./Cliente.txt");
                fw = new FileWriter(archivo, false);
                bw = new BufferedWriter(fw);
                for (Cliente t : clientes) {
                    bw.write("[\n"
                            + "\t" + t.getNombre() + ", \n"
                            + "\t" + t.getEdad() + ", \n"
                            + "\t" + t.getProfesion() + ", \n"
                            + "\t" + t.getCarros_Comprados() + ", \n"
                            + "\t" + t.getSueldo_Disponible() + ", \n"
                            + "]-\n");
                }
                bw.flush();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            bw.close();
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error y no se agregó nada");
        }
        JOptionPane.showMessageDialog(this, "Cliente agregado exitosamente");
        tf_NombreCliente.setText("");
        tf_Edad.setValue(0);
        tf_Profesion.setText("");
        tf_CarrosComprados.setValue(0);
        tf_SueldoDisponible.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    ArrayList<Vehiculo> vehiculos = new ArrayList();
    ArrayList<Vendedor> vendededores = new ArrayList();
    ArrayList<Cliente> clientes = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVehiculo;
    private javax.swing.JButton AgregarVendedor;
    private javax.swing.JButton ColorBttn;
    private javax.swing.JPanel CrearCliente;
    private javax.swing.JPanel CrearVehiculo;
    private javax.swing.JPanel CrearVendedor;
    private javax.swing.JPanel CrearVentas;
    private javax.swing.JTextField PrecioVenta;
    private javax.swing.JTabbedPane TabsPrincipales;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner tf_Año;
    private javax.swing.JSpinner tf_CantidadCarros;
    private javax.swing.JTextField tf_CantidadDinero;
    private javax.swing.JSpinner tf_CarrosComprados;
    private javax.swing.JSpinner tf_Edad;
    private javax.swing.JTextField tf_Marca;
    private javax.swing.JTextField tf_Modelo;
    private javax.swing.JTextField tf_NombreCliente;
    private javax.swing.JTextField tf_NombreVendedor;
    private javax.swing.JTextField tf_Profesion;
    private javax.swing.JTextField tf_SueldoDisponible;
    // End of variables declaration//GEN-END:variables
}
